# Generated by Django 6.0.4 on 2026-05-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_staff_is_available_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="postcode",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
