# Generated by Django 6.0.4 on 2026-05-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_staff_latitude_staff_longitude_staff_postcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="cancelled_shifts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staff",
            name="completed_shifts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staff",
            name="disco_rank",
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name="staff",
            name="late_arrivals",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staff",
            name="no_shows",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staff",
            name="positive_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
