# Generated by Django 6.0.4 on 2026-05-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_staff_cancelled_shifts_staff_completed_shifts_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="disco_rank",
        ),
    ]
