# Generated by Django 6.0.4 on 2026-05-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_remove_staff_disco_rank"),
        ("disco_app", "0006_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="skills",
            field=models.ManyToManyField(blank=True, to="disco_app.skill"),
        ),
    ]
