# Generated by Django 6.0.4 on 2026-06-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_favouritestaff"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="wants_shift_emails",
            field=models.BooleanField(default=True),
        ),
    ]
