# Generated by Django 6.0.4 on 2026-04-30 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("postcode", models.CharField(max_length=20)),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant"),
                            ("bar", "Bar"),
                            ("pub", "Pub"),
                            ("club", "Club"),
                            ("hotel", "Hotel"),
                            ("cafe", "Cafe"),
                            ("other", "Other"),
                        ],
                        default="restaurant",
                        max_length=50,
                    ),
                ),
                (
                    "operators",
                    models.ManyToManyField(
                        related_name="sites", to="authentication.operator"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_required",
                    models.CharField(
                        choices=[
                            ("chef", "Chef"),
                            ("bartender", "Bartender"),
                            ("waiting_staff", "Waiting Staff"),
                            ("barista", "Barista"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hourly rate offered for this shift",
                        max_digits=6,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("requested", "Requested"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shifts",
                        to="authentication.staff",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="disco_app.site",
                    ),
                ),
            ],
        ),
    ]
