# Generated by Django 6.0.4 on 2026-05-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disco_app", "0003_site_lat_long"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftrequest",
            name="source",
            field=models.CharField(
                choices=[("application", "Application"), ("invite", "Invite")],
                default="application",
                max_length=20,
            ),
        ),
    ]
