# Generated by Django 6.0.4 on 2026-05-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disco_app", "0004_shiftrequest_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
