# Generated by Django 6.0.4 on 2026-05-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disco_app", "0005_alter_shiftrequest_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
